framework:
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true
    session:
        enabled: true
        handler_id: null
        storage_factory_id: 'session.storage.factory.native'
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: 'session.storage.factory.mock_file'
